// Mocks generated by Mockito 5.4.6 from annotations
// in mpx/test/mocks/video_scanner_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mpx/features/library/data/datasources/local_video_scanner.dart'
    as _i2;
import 'package:mpx/features/library/domain/entities/video_file.dart' as _i4;
import 'package:mpx/features/library/domain/entities/video_folder.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoScanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoScanner extends _i1.Mock implements _i2.VideoScanner {
  MockVideoScanner() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.VideoFile> get onVideoAdded => (super.noSuchMethod(
        Invocation.getter(#onVideoAdded),
        returnValue: _i3.Stream<_i4.VideoFile>.empty(),
      ) as _i3.Stream<_i4.VideoFile>);

  @override
  _i3.Stream<String> get onVideoRemoved => (super.noSuchMethod(
        Invocation.getter(#onVideoRemoved),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  bool get isWatching => (super.noSuchMethod(
        Invocation.getter(#isWatching),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<List<_i5.VideoFolder>> scanForVideos({
    bool? forceRefresh = false,
    bool? enableWatching = true,
    dynamic Function(
      double,
      String,
    )? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanForVideos,
          [],
          {
            #forceRefresh: forceRefresh,
            #enableWatching: enableWatching,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i3.Future<List<_i5.VideoFolder>>.value(<_i5.VideoFolder>[]),
      ) as _i3.Future<List<_i5.VideoFolder>>);

  @override
  _i3.Future<List<_i4.VideoFile>> getVideosInFolder(String? folderPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideosInFolder,
          [folderPath],
        ),
        returnValue: _i3.Future<List<_i4.VideoFile>>.value(<_i4.VideoFile>[]),
      ) as _i3.Future<List<_i4.VideoFile>>);

  @override
  _i3.Future<void> startWatching() => (super.noSuchMethod(
        Invocation.method(
          #startWatching,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopWatching() => (super.noSuchMethod(
        Invocation.method(
          #stopWatching,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
